# This file contains values from Cookiecutter

default_context:
  project_name: "drpy"
  project_description: "Tools for working with dimentionality reduction"
  organization: "ansolesen"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "ansolesen"
  email: "ansolesen@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
